Repository tylerpporter/find_my_market_fe, pull requests merged in 2020-07, with the labels that each got.

#13 Feature/search map
  assets/FMM-logo.png
  components/Header/Header.js
  components/Home/Home.js
  components/ListItem/ListItem.js
  components/Login/Login.js
  components/MainNav/MainNav.js
  components/Map/Map.js
  components/SearchNav/SearchNav.js
Labels: EPIC 03, EPIC 6, FE

#15 Feature/testing cleanup
  .gitignore
  README.md
  apiCalls.js
  app.json
  assets/FMM-logo.png
  assets/FMM_banner_logo_final.png
  assets/FMM_icon_no_border.png
  assets/FMM_logo_final.png
  components/App/App.js
  components/App/App.test.js
  components/Footer/Footer.js
  components/Header/Header.js
  components/Header/Header.test.js
  components/Home/Home.js
  components/Home/Home.test.js
  components/ListItem/ListItem.js
  components/ListItem/ListItem.test.js
  components/Login/Login.js
  components/Login/Login.test.js
  components/Map/Map.js
  components/SearchNav/SearchNav.js
  components/SearchNav/SearchNav.test.js
  package-lock.json
  package.json
  sample-data.js
Labels: EPIC 07, EPIC 6, FE

#17 Travis
  .travis.yml
Labels: FE

#22 Feature/auth login refactor
  apiCalls.js
  components/App/App.js
  components/App/App.test.js
  components/Header/Header.js
  components/Home/Home.js
  components/Home/Home.test.js
  components/Login/Login.js
  components/Login/Login.test.js
  components/Register/Register.js
  components/SignIn/SignIn.js
Labels: FE

#23 Feature/create favorites
  apiCalls.js
  assets/FMM_icon_no_border_favorites.png
  components/App/App.test.js
  components/FavMarkers/FavMarkers.js
  components/Header/Header.js
  components/Home/Home.js
  components/Login/Login.js
  components/Map/Map.js
  components/Markers/Markers.js
  components/Register/Register.js
  components/SearchNav/SearchNav.js
  components/SignIn/SignIn.js
Labels: EPIC 08, FE
