Repository tylerpporter/find_my_market_fe, pull requests merged in 2020-08, with the labels that each got.

#24 Feature/date filtering
  .env
  apiCalls.js
  app.config.js
  components/Header/Header.js
  components/Header/Header.test.js
  components/Login/Login.js
  components/Modals/RegisterModal.js
  components/Modals/SignInModal.js
  components/MyDatePicker/MyDatePicker.js
  components/Register/Register.js
  components/SearchNav/SearchNav.js
  components/SignIn/SignIn.js
  package-lock.json
  package.json
Labels: EPIC 03, FE

#27 Feature/refactor favorites
  apiCalls.js
  components/FavMarkers/FavMarkers.js
  components/Header/Header.js
  components/Home/Home.js
  components/Map/Map.js
  components/SignIn/SignIn.js
Labels: EPIC 08, FE

#28 Feature/profile
  apiCalls.js
  components/App/App.js
  components/FavMarkers/FavMarkers.js
  components/Header/Header.js
  components/Header/Header.test.js
  components/Home/Home.js
  components/Login/Login.js
  components/Map/Map.js
  components/Modals/RegisterModal.js
  components/Modals/SignInModal.js
  components/Profile/Profile.js
  components/Register/Register.js
  components/SignIn/SignIn.js
  package-lock.json
  package.json
  utilities/UserPermissions.js
Labels: FE

#29 Feature/list view profile
  apiCalls.js
  components/FavMarketList/FavMarketList.js
  components/Header/Header.js
  components/Profile/Profile.js
Labels: EPIC 09, FE

#30 Refactor/modals
  components/App/App.js
  components/Header/Header.js
  components/HeaderView/HeaderView.js
  components/Home/Home.js
  components/Login/Login.js
  components/LoginContainer/LoginContainer.js
  components/LoginContainer/LoginContainer.test.js
  components/LoginView/LoginView.js
  components/Modals/FilterModal.js
  components/Modals/HamburgerModal.js
  components/Modals/ProfileUpdateModal.js
  components/Modals/RegisterModal.js
  components/Modals/SignInModal.js
  components/Modals/WelcomeModal.js
  components/Profile/Profile.js
Labels: FE

#31 Refactor/profile
  components/Map/Map.js
  components/Markers/Markers.js
  components/MyDatePicker/MyDatePicker.js
  components/Profile/Profile.js
  components/ProfileImage/ProfileImage.js
  components/ProfileInfo/ProfileInfo.js
Labels: FE
